### ISSUE TITLE
ログイン・サインイン画面

### ISSUE THREAD

**Issue by thoth000** [stamp-team/chat-flutter#4]
# UIイメージ
<img  width="200px" src="https://user-images.githubusercontent.com/51738889/84262489-ad3ab900-ab58-11ea-95a0-17298d1bc2a9.png"> <img  width="200px" src="https://user-images.githubusercontent.com/51738889/84262610-d9eed080-ab58-11ea-9854-fb88dbb8d905.png">

# 詳細
それぞれ下のSIGN IN , LOG INで切り替える

**Comment by thoth000** [comment]
初めに開く画面は Sign inの方でお願いします

**Comment by PictoMki** [comment]
ここ新規登録ってSIGN UPですよね？
一旦ログイン画面はSIGN INで新規登録画面はSIGN UPにしますね！

**Comment by thoth000** [comment]
すいません笑
修正ありがとうございます！
